version: 2
jobs:
  build:
    working_directory: ~/mapcss-parse
    docker:
      - image: circleci/node:10.7.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install dependencies
          command: 'npm install'
      - run:
          name: build
          command: 'npm run build'
      - run:
          name: test
          command: 'npm test'
